apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: build-trusted-artifacts
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-build-tenant/build-trusted-artifacts/build-trusted-artifacts@sha256:aa288fd08f0eb1c39b926caf8fa760276b9cc979a9b13d16d66adff5322a1fa7
        name: container-image
        resources: {}
status: {}
