apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: build-trusted-artifacts
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-build-tenant/build-trusted-artifacts/build-trusted-artifacts@sha256:f7808bd0b8aeca00d7ff5725e299ce4df8ada515cb3682a0888322c75c34d042
        name: container-image
        resources: {}
status: {}
