apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: build-trusted-artifacts
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-build-tenant/build-trusted-artifacts/build-trusted-artifacts@sha256:78f559ecd9c68f1321814af96056a23687efda58196575eb2d2eb4fcd1b89535
        name: container-image
        resources: {}
status: {}
