apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: build-trusted-artifacts
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-build-tenant/build-trusted-artifacts/build-trusted-artifacts@sha256:6e959da77767bcdd517a7ae7bc55875e694aea36067aaebaa17f3a0a678f3c21
        name: container-image
        resources: {}
status: {}
