apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: build-trusted-artifacts
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-build-tenant/build-trusted-artifacts/build-trusted-artifacts@sha256:1b0b5e2175fcaa3e1ed5e1d01f1b67fb280bb5c73e50e741c75cf044f0ea2e13
        name: container-image
        resources: {}
status: {}
