apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-trusted-artifacts
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-trusted-artifacts
    app.kubernetes.io/part-of: build-trusted-artifacts
  name: build-trusted-artifacts
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: build-trusted-artifacts
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: build-trusted-artifacts
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-build-tenant/build-trusted-artifacts/build-trusted-artifacts@sha256:45cb2266c1f34612f7aab38731bad657d2a3b91c57dd58e9a408732558e1280d
        imagePullPolicy: Always
        name: container-image
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
